version: '3.8'
services:

  users_service:
    build:
      context: ./users_service
    container_name: users_service
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db/

  mongo-drop:
    image: mongo:6.0
    container_name: mongo-drop
    depends_on:
      - mongodb
    entrypoint: |
      /bin/bash -c '
        echo "Dropping database..." &&
        apt-get update && apt-get install -y mongodb-database-tools &&
        mongo mongodb://mongodb/users --eval "db.dropDatabase()"
      '

  mongo-seed-users:
    image: mongo:6.0
    container_name: mongo-seed-users
    depends_on:
      - mongo-drop
    volumes:
      - ./users_service/users.json:/dataset/users.json
    entrypoint: |
      /bin/bash -c '
        echo "Importing Users..." &&
        apt-get update && apt-get install -y mongodb-database-tools &&
        mongoimport --host mongodb -d users --collection users --type json --file /dataset/users.json --jsonArray
      '

volumes:
  mongo-data:
